### ISSUE TITLE
Error when enabling the plugin

### ISSUE THREAD

**Issue by Hubaxis7** [likemusic/CKEditorTableCellsSelection#10]
When I enabled the plugin (ckeditortablecellsselection) to Drupal /admin/config/content/ckeditor/ I can't turn on CKeditor when creating content.
I use //cdn.ckeditor.com/4.7.3/full-all and CKEditorTableCellsSelection v0.0.2-alpha

![screenshot_00](https://user-images.githubusercontent.com/22938004/32373498-98151868-c0aa-11e7-81f3-e19fce2ee57c.png)

**Comment by likemusic** [comment]
Seems that jQuery not used on this page or loaded after CKEditor initialization. Make sure that jQuery is loaded on page and CKEditor initialization happens after that.

May be it can help you - https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_jquery

**Comment by Hubaxis7** [comment]
I'm sorry, but I'm not strong at scripting and I would be very grateful if you could help me run your wonderful plugin.

**Comment by likemusic** [comment]
I'm sorry, but I think that I won't have time for this. I have some bug-reports that are not fixed over years :(  In addition, I'm new to Drupal.

Please, provide what version of Drupal are you using? If CKEditor doesn't exists in Drupal out of the box, please provide what plugins/extensions (with versions) are you using?

**Comment by Hubaxis7** [comment]
I use 7.56 Drupal, CKEditor 4.7.3 (Full). All the other plugins I disabled. I tried your plugin on different sites, but only get errors.

**Comment by likemusic** [comment]
I found that from May 2017 exists plugin with the same functionality written by CKSource that available for v4.7 - https://ckeditor.com/cke4/addon/tableselection . Try to use it instead.

**Comment by Hubaxis7** [comment]
Thanks for the help and your work.
